apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"3903","prometheus.io/scheme":"http","prometheus.io/scrape":"logs-exporter"},"name":"logs-exporter","namespace":"monitoring"},"spec":{"clusterIP":"None","ports":[{"name":"metrics","port":3903,"protocol":"TCP","targetPort":3903}],"selector":{"k8s-app":"logs-exporter"}}}
    prometheus.io/path: /metrics
    prometheus.io/port: "3903"
    prometheus.io/scheme: http
    prometheus.io/scrape: logs-exporter
  creationTimestamp: 2020-05-12T10:27:29Z
  name: logs-exporter
  namespace: monitoring
  resourceVersion: "213612924"
  selfLink: /api/v1/namespaces/monitoring/services/logs-exporter
  uid: 2ef3afd7-943b-11ea-bda3-5254003fdaeb
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 3903
    protocol: TCP
    targetPort: 3903
  selector:
    k8s-app: logs-exporter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
