apiVersion: v1
data:
  invoke_time.mtail: "counter log_monitor by process_time_ms,logfile\nhistogram log_monitor_process_time_ms
    buckets 300,600,1000,5000,10000,30000 by logfile\n\ngetfilename() !~ /(invoker.log|provider.log)$/
    {\n  stop\n}\n\n/time: (\\d+) ms/ {\n \n  # 直方图\n  $1 < 300 {\n    log_monitor[\"[-,300)\",getfilename()]++\n
    \ }\n  $1 >= 300 && $1 < 600 {\n    log_monitor[\"[300,600)\",getfilename()]++\n
    \ }\n  $1 >= 600 && $1 < 1000 {\n    log_monitor[\"[600,1000)\",getfilename()]++\n
    \ }\n  $1 >= 1000 && $1 < 5000 {\n    log_monitor[\"[1000,5000)\",getfilename()]++\n
    \ }\n  $1 >= 5000 && $1 < 10000 {\n    log_monitor[\"[5000,10000)\",getfilename()]++\n
    \ }\n  $1 >= 10000 && $1 < 30000 {\n    log_monitor[\"[10000,30000)\",getfilename()]++\n
    \ }\n  $1 >= 30000 {\n    log_monitor[\"[30000,-)\",getfilename()]++\n  }\n  #
    累积直方图\n  log_monitor_process_time_ms[getfilename()] = $1\n\n}\n"
  key_words.mtail: |
    counter log_monitor by key_words,logfile

    getfilename() !~ /(stdout.log|stderr.log|catalina.out)$/ {
      stop
    }

    /(java.lang.OutOfMemoryError|java.lang.ExceptionInInitializerError|java.lang.IllegalAccessError|java.lang.IncompatibleClassChangeError|java.lang.InternalError|java.lang.NoClassDefFoundError|java.lang.NoSuchFieldError|java.lang.NoSuchMethodError|java.lang.OutOfMemoryError|java.lang.StackOverflowError|java.lang.ThreadDeath|java.lang.UnsatisfiedLinkError|java.lang.UnsupportedClassVersionError|java.lang.VerifyError|java.lang.VirtualMachineError|rollback failed|requestTimeout|java.sql.SQLException: Access denied for user)/ {

      log_monitor[$1,getfilename()]++

    }
  var_log_message.mtail: |
    counter log_monitor by key_words,logfile

    getfilename() !~ /(messages)$/ {
      stop
    }

    /(out of memory: Kill process)/ {
      log_monitor[$1,getfilename()]++
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"invoke_time.mtail":"counter log_monitor by process_time_ms,logfile\nhistogram log_monitor_process_time_ms buckets 300,600,1000,5000,10000,30000 by logfile\n\ngetfilename() !~ /(invoker.log|provider.log)$/ {\n  stop\n}\n\n/time: (\\d+) ms/ {\n \n  # 直方图\n  $1 \u003c 300 {\n    log_monitor[\"[-,300)\",getfilename()]++\n  }\n  $1 \u003e= 300 \u0026\u0026 $1 \u003c 600 {\n    log_monitor[\"[300,600)\",getfilename()]++\n  }\n  $1 \u003e= 600 \u0026\u0026 $1 \u003c 1000 {\n    log_monitor[\"[600,1000)\",getfilename()]++\n  }\n  $1 \u003e= 1000 \u0026\u0026 $1 \u003c 5000 {\n    log_monitor[\"[1000,5000)\",getfilename()]++\n  }\n  $1 \u003e= 5000 \u0026\u0026 $1 \u003c 10000 {\n    log_monitor[\"[5000,10000)\",getfilename()]++\n  }\n  $1 \u003e= 10000 \u0026\u0026 $1 \u003c 30000 {\n    log_monitor[\"[10000,30000)\",getfilename()]++\n  }\n  $1 \u003e= 30000 {\n    log_monitor[\"[30000,-)\",getfilename()]++\n  }\n  # 累积直方图\n  log_monitor_process_time_ms[getfilename()] = $1\n\n}\n","key_words.mtail":"counter log_monitor by key_words,logfile\n\ngetfilename() !~ /(stdout.log|stderr.log|catalina.out)$/ {\n  stop\n}\n\n/(java.lang.OutOfMemoryError|java.lang.ExceptionInInitializerError|java.lang.IllegalAccessError|java.lang.IncompatibleClassChangeError|java.lang.InternalError|java.lang.NoClassDefFoundError|java.lang.NoSuchFieldError|java.lang.NoSuchMethodError|java.lang.OutOfMemoryError|java.lang.StackOverflowError|java.lang.ThreadDeath|java.lang.UnsatisfiedLinkError|java.lang.UnsupportedClassVersionError|java.lang.VerifyError|java.lang.VirtualMachineError|rollback failed|requestTimeout|java.sql.SQLException: Access denied for user)/ {\n\n  log_monitor[$1,getfilename()]++\n\n}\n","var_log_message.mtail":"counter log_monitor by key_words,logfile\n\ngetfilename() !~ /(messages)$/ {\n  stop\n}\n\n/(out of memory: Kill process)/ {\n  log_monitor[$1,getfilename()]++\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"mtail-config","namespace":"monitoring"}}
  creationTimestamp: 2020-05-12T10:39:27Z
  name: mtail-config
  namespace: monitoring
  resourceVersion: "226286662"
  selfLink: /api/v1/namespaces/monitoring/configmaps/mtail-config
  uid: dabdd8e9-943c-11ea-bda3-5254003fdaeb
